### ISSUE TITLE
User Flow Mocks

### ISSUE THREAD

**Issue by jhf1203** [WasteOfADrumBum/project-iii#25]
![1-landing](https://user-images.githubusercontent.com/66701459/98581583-b6f35480-228f-11eb-8645-d418eeb5415b.png)
____________

![2-register1](https://user-images.githubusercontent.com/66701459/98581585-b6f35480-228f-11eb-9134-88e97987f603.png)
____________

![3-register2](https://user-images.githubusercontent.com/66701459/98581588-b6f35480-228f-11eb-8304-556426fde146.png)
____________

![4-dashboard](https://user-images.githubusercontent.com/66701459/98581591-b78beb00-228f-11eb-9f53-abe77a788a36.png)
____________

![5-addnew](https://user-images.githubusercontent.com/66701459/98585789-cc6b7d00-2295-11eb-9511-ddf623560293.png)
____________

![6-viewexisting](https://user-images.githubusercontent.com/66701459/98585791-cd041380-2295-11eb-878b-ca5ab1811b0b.png)
____________

![7-to-and-from](https://user-images.githubusercontent.com/66701459/98588839-59b0d080-229a-11eb-88ee-a4a7e3450a35.png)
____________

![8-maps](https://user-images.githubusercontent.com/66701459/98588841-5a496700-229a-11eb-9b5b-181402e4195e.png)

**Comment by WasteOfADrumBum** [comment]
Love it!
